
database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: johnschindler

  # the password
  #password:

  # the JDBC URL
  url: jdbc:postgresql://localhost/rangersstats

